### ISSUE TITLE
Update example project with .codecov.yml

### ISSUE THREAD

**Issue by jessesquires** [codecov/example-swift#10]
Would be nice to have an example of this in the repo 😄

**Comment by stevepeak** [comment]
The `codecov.yml` is not *required* and inherits its settings from out application defaults. I'm not sure what content we would include in this example file... Suggestions?

**Comment by stevepeak** [comment]
Closing because the `codecov.yml` is not a required file to upload coverage. We do welcome a pull request with a yaml is a specific configuration is suggested. Thank you!
