### ISSUE TITLE
How to ignore test coverage of Pods

### ISSUE THREAD

**Issue by PanosSakkos** [codecov/example-swift#11]
With the default setup of codecov for xcode projects I'm getting coverage reports that include the cocoapods (repo/Pods directory). How can we ignore the code coverage of the Pods?

Thanks!

**Comment by stevepeak** [comment]
Sure! You can add the following:

`bash <(curl -s https://codecov.io/bash) -J 'YourProjectName'`

This will filter out the unwanted data.

**Comment by PanosSakkos** [comment]
Thanks @stevepeak !

As far as I remember I tried that but it didn't work. I will try it again tonight :smile: 

Thanks and keep up the great work!

**Comment by PanosSakkos** [comment]
It worked, thanks! :clap:
