### ISSUE TITLE
API for specifying multiple App/Framework targets?

### ISSUE THREAD

**Issue by Ben-G** [codecov/example-swift#12]
I want to use codecov on a project that has multiple targets (one App target, one framework target) and still use the `-J` option to speed up code coverage generation. I couldn't find a description on how to do this. I took a look at the script and noticed it uses the `-J` argument and passes it to `grep`. So I came up with a workaround that relies on the `grep` alternation operator:

```
bash <(curl -s https://codecov.io/bash) -J "AppName\|FrameworkTargetName"
```

This works, but it's problematic since I'm relying on implementation details of the script. Do you think it would be possible to extend the script to take multiple arguments for the target name?

**Comment by stevepeak** [comment]
Hey @Ben-G would this work?

```
bash <(curl -s https://codecov.io/bash) -J "AppName" -J "FrameworkTargetName"
```
> This is  currently supported.

Let me know if this works out 👍

**Comment by Ben-G** [comment]
This works, thx! I just noticed that you had already mentioned in the Readme that this is possible.

Sorry & thx 👍
