### ISSUE TITLE
Xcode 8 and Swift 3 support

### ISSUE THREAD

**Issue by yannickl** [codecov/example-swift#14]
The coverage does not seem to work on codecov with Xcode 8 and Swift 3.

As example you can take a look at my [DynamicColor](https://github.com/yannickl/DynamicColor) project and its corresponding [travis logs](https://travis-ci.org/yannickl/DynamicColor) and [codecov results](https://codecov.io/gh/yannickl/DynamicColor).

**Comment by stevepeak** [comment]
Hey @yannickl The results we have uploaded indeed express 0% coverage ([see here][0])

The issue is on coverage collection with xcode. There is likely a configuration issue that will resolve this. Are you able to run tests locally and discover the same result?

> PS cool project 👍 


[0]: https://codecov.s3.amazonaws.com/v4/raw/2016-09-05/45160C5BB93B8C9046BECE0B17CF31C2/a68c4ab95899c8f8e02d6f83fb97559c38e7783d/7b5b5d3b-720f-4f99-a756-7b119296b740.txt

**Comment by yannickl** [comment]
Yes indeed I have the same issue locally... I need to investigate more why it does not work with Xcode 8... I don't know what changed between Xcode 7 and 8.

And thank you for the nice words 👍

**Comment by FranzBusch** [comment]
I think the format of the generated file changed. I tried using slather to parse the file and it is throwing unsupported file format. So I guess something changed there

**Comment by stevepeak** [comment]
@FranzBusch good idea, but I do not see an issue with the report format. You can clearly see the lines are tracked and reporting `0` for missed, as seen below.

```
      0|   45|  public convenience init(L: CGFloat, a: CGFloat, b: CGFloat) {
      0|   46|    let clippedL = clip(L, 0, 100)
      0|   47|    let clippedA = clip(a, -128, 127)
      0|   48|    let clippedB = clip(b, -128, 127)
```

I still believe this is an issue with xcode tracking the coverage metrics. Have you seen the reports in xcode show accurate results yet?

**Comment by yannickl** [comment]
The local `DynamicColor.framework.coverage.txt` gives me that:

```
      0|   45|  public convenience init(L: CGFloat, a: CGFloat, b: CGFloat) {
      0|   46|    let clippedL = clip(L, 0, 100)
      0|   47|    let clippedA = clip(a, -128, 127)
      0|   48|    let clippedB = clip(b, -128, 127)
```

While Xcode (and its coverage tool) give me a good result:
<img width="900" alt="screen shot 2016-09-07 at 17 39 46" src="https://cloud.githubusercontent.com/assets/798235/18318581/7d927a96-7522-11e6-918d-4a75aaa3237a.png">

So this is either an Xcode bug or it missing a flag somewhere...

**Comment by stevepeak** [comment]
@yannickl the `0` indicates a missed line... I'm thinking this should be a bug reported to xcode. Thoughts?

**Comment by yannickl** [comment]
@stevepeak I'm not an expert with coverage files... I've asked to one Xcode engineer if he could help us (https://twitter.com/yannickloriot/status/773551806832058368), otherwise I'll fill a radar to Apple.

**Comment by na-gupta** [comment]
@yannickl We are seeing similar issues with incorrect code coverage reporting with xcode 8 /swift 3. Were you able to find a fix or workaround for this or have you reported it as a bug?

**Comment by stevepeak** [comment]
We have not heard yet on what the issue(s) are. Codecov did not change the technique of using llvm-cov to process reports. We do believe this is an issue with XCode's Profdata. I'll try again to reach out to someone for more clarification and help.

**Comment by na-gupta** [comment]
@stevepeak Appreciate you looking into it

**Comment by yannickl** [comment]
@na-gupta no I didn't putted a radar yet and I didn't found workaround neither... I'll add a report  tomorrow.

**Comment by yannickl** [comment]
I just open a report in the Apple's bug report (https://openradar.appspot.com/radar?id=5600392557625344). I believe they will be reactive... But without direct contact I have no much hope...

**Comment by stevepeak** [comment]
@yannickl nice job 👍

**Comment by yannickl** [comment]
@stevepeak I received a mail from the Apple support:

```
According to the problem description, the code coverage workflow is working as expected in the IDE but failing on the command line. The command line invocation is going through a third party code coverage service. Here's the command:

From https://travis-ci.org/yannickl/DynamicColor:

    xcodebuild -project DynamicColorExample.xcodeproj -scheme OSXTests -sdk macosx -configuration Release GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ONLY_ACTIVE_ARCH=YES test | xcpretty -c

Apple doesn't ship the xcpretty tool, so we're not responsible for any bugs in it. We have updated the data formats for raw and indexed profiles with Xcode 8 -- perhaps xcpretty needs to be updated to reflect this?

At any rate, we can get correct coverage data by building the user's project locally, running the tests, invoking llvm-profdata, and then calling llvm-cov. E.g:

    $ xcodebuild -project DynamicColorExample.xcodeproj -scheme OSXTests -sdk macosx -configuration Release -enableCodeCoverage=YES test
    $ cd into DerivedData...
    $ xcrun llvm-profdata show --all-functions Build/Intermediates/CodeCoverage/Coverage.profdata # Verify the profdata.
    $ xcrun llvm-cov show -instr-profile Build/Intermediates/CodeCoverage/Coverage.profdata /Build/Intermediates/CodeCoverage/Products/Release/OSXTests.xctest/Contents/MacOS/OSXTests
```

So it seems that the issue comes from the xcpretty tool...

I updated the travis config file in my [project](https://github.com/yannickl/DynamicColor) but the result in codecov is always wrong...

**Comment by stevepeak** [comment]
@yannickl thank you for following up.

Can you forward me this contact you have at Apple support?

What [Codecov does](https://github.com/codecov/codecov-bash/blob/e7c0c15393bbab2dd8028c9a3c0546d7cb9badb4/codecov#L165-L182) is very straight forward and has not changed in months. I'm still **very confident** this is an issue with xcodebuild's resulting Profdata.

**Comment by stevepeak** [comment]
@yannickl if you run the llvm-cov command does it output accurate coverage results?

**Comment by stevepeak** [comment]
@yannickl can you please try this method:

```yml
language: generic
sudo: required
osx_image: xcode8
script:
  - swift package generate-xcodeproj
  - xcodebuild -scheme RequestBuilder -enableCodeCoverage YES test  # instead of swift test
after_success:
  - bash <(curl -s https://codecov.io/bash)
```

> As posted here: https://github.com/codecov/support/issues/142#issuecomment-249045205

**Comment by yannickl** [comment]
@stevepeak Sorry for the late. Unfortunately I don't have a direct mail for the Apple support contact. I have to use their bug reporter.

The llvm-cov seems to work fine with the `macOS` tests, but It fails with `iOS`...

- On `macOS`:
```bash
$ xcodebuild -project DynamicColorExample.xcodeproj -scheme OSXTests -sdk macosx -configuration Release -enableCodeCoverage=YES test
$ xcrun llvm-cov report -instr-profile Coverage.profdata Products/Release/OSXTests.xctest/Contents/MacOS/OSXTests 
```
The result:
```
Filename                                                                                 Regions    Miss   Cover Functions  Executed
------------------------------------------------------------------------------------------------------------------------------------
/Users/yannickloriot/Development/test/DynamicColor/Sources/Array.swift                         1       0 100.00%         1   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor+Deriving.swift         8       0 100.00%         8   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor+HSB.swift              5       0 100.00%         1   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor+HSL.swift              2       0 100.00%         2   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor+Lab.swift              8       0 100.00%         2   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor+Mixing.swift          19       0 100.00%         8   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor+RGBA.swift             7       0 100.00%         3   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor+XYZ.swift              8       0 100.00%         2   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor.swift                 14       0 100.00%         7   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicGradient.swift              21       0 100.00%         3   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/HSL.swift                          31       0 100.00%         9   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/Utils.swift                         3       0 100.00%         3   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Tests/DynamicColor+HSBTests.swift          44      22  50.00%         4   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Tests/DynamicColor+HSLTests.swift          24      11  54.17%         2   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Tests/DynamicColor+RGBATests.swift         35      13  62.86%         7   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Tests/DynamicColor+XYZTests.swift          50      24  52.00%         2   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Tests/DynamicColorArrayTests.swift         36      16  55.56%         3   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Tests/DynamicColorLabTests.swift           68      33  51.47%         2   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Tests/DynamicColorTests.swift             234     106  54.70%        24   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Tests/DynamicGradientTests.swift           21       4  80.95%         2   100.00%
------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                        639     229  64.16%        95   100.00%
```

- on `iOS`:
```bash
$ xcodebuild -project DynamicColorExample.xcodeproj -scheme iOSTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage=YES test
$ xcrun llvm-cov report -instr-profile Coverage.profdata Products/Release-iphonesimulator/DynamicColorExample.app/DynamicColorExample
```
The result:
```
Filename                                                                                      Regions    Miss   Cover Functions  Executed
-----------------------------------------------------------------------------------------------------------------------------------------
/Users/yannickloriot/Development/test/DynamicColor/Examples/iOSExample/AppDelegate.swift            6       4  33.33%         6    33.33%
/Users/yannickloriot/Development/test/DynamicColor/Examples/iOSExample/ColorCellView.swift          3       0 100.00%         1   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Examples/iOSExample/ViewController.swift        10       1  90.00%         6   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/Array.swift                              1       0 100.00%         1   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor+Deriving.swift              8       0 100.00%         8   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor+HSB.swift                   4       4   0.00%         4     0.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor+HSL.swift                   2       2   0.00%         2     0.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor+Lab.swift                   8       8   0.00%         2     0.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor+Mixing.swift               19      14  26.32%         8    37.50%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor+RGBA.swift                  7       6  14.29%         7    14.29%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor+XYZ.swift                   8       8   0.00%         2     0.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicColor.swift                      14      11  21.43%         7    28.57%
/Users/yannickloriot/Development/test/DynamicColor/Sources/DynamicGradient.swift                   21       5  76.19%         3   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/HSL.swift                               31       4  87.10%         9   100.00%
/Users/yannickloriot/Development/test/DynamicColor/Sources/Utils.swift                              3       1  66.67%         3    66.67%
-----------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                             145      68  53.10%        69    55.07%
```

May be I missing something but I don't know why?

To finish I tried with SPM (Swift Package Manager) and I have the same issue. Everything is ok with `macOS` but it does not work with `iOS`.

**Comment by stevepeak** [comment]
@yannickl can you try the `llvm-cov` against these metrics to see if the resulting file is 0% coverage?

**Comment by yannickl** [comment]
@stevepeak I think I found a solution. I recreated a new scheme in Xcode 8 to test the iOS platform and it seems to work with the same previous command lines. I'm updating my project and I'll test on travis.

**Comment by yannickl** [comment]
@stevepeak I've updated the[ DynamicColor](https://github.com/yannickl/DynamicColor) travis config. It works (https://travis-ci.org/yannickl/DynamicColor/builds/162218473#L633-L657) locally but the codecov bash does not find any report.

Any clue?

**Comment by stevepeak** [comment]
> CC https://github.com/yannickl/DynamicColor/pull/16#issuecomment-249427357

Thanks to @yannickl we may have an answer here:
1. update the iOS test scheme with Xcode 8
2. do not use `xcpretty`. Seems broken with code coverage Xcode 8

@na-gupta @FranzBusch let me know if this works for you 👍

**Comment by na-gupta** [comment]
@stevepeak @yannickl  It does look better now. Thanks for your help!

**Comment by stevepeak** [comment]
Thank you everyone for your help and patience 👍
