### ISSUE TITLE
Issue test coverage

### ISSUE THREAD

**Issue by remirobert** [codecov/example-swift#19]
I have a iOS app, running snapshot, and unit tests.
Codecov takes in charge the pods, and the tests files, so I don't have the right coverage value.

Here the project (it's opensource) : https://github.com/remirobert/go-mobile-twitter-stream

**Comment by remirobert** [comment]
I think the app code is not covered for some reason. And the txt file generate by Xcode is empty.
Is there any way to ignore the other coverage report? For pods, and tests?
<img width="1175" alt="screen shot 2017-09-12 at 21 47 07" src="https://user-images.githubusercontent.com/3276768/30345032-f2f41b00-9803-11e7-9630-01b0c9670e22.png">

**Comment by stevepeak** [comment]
You can ignore Pods from your `codecov.yml`

```yaml
ignore:
  - Pods
  - Tests
```

We suggest you use the new `xcodeplist` ahead of our official launch soon.

```sh
bash <(curl -s https://codecov.io/bash) -X xcodeplist
```

**Comment by stevepeak** [comment]
Please contact support in-app or Slack to ask more repository specific questions. Thanks!
