### ISSUE TITLE
CodeCov reporting "Swift: no coverage data found."

### ISSUE THREAD

**Issue by Danappelxx** [codecov/example-swift#5]
Error:
```
Swift: no coverage data found. Learn more at: https://github.com/codecov/example-swift
```

[Travis log](https://travis-ci.org/Danappelxx/SwiftMongoDB/builds/92194916#L2217)
[.travis.yml](https://raw.githubusercontent.com/Danappelxx/SwiftMongoDB/7e1ea937ddbf95723a10c7f2cd4122dbe1cc82d1/.travis.yml)

The "gather coverage data" checkbox is ticked.

What am I doing wrong? Thanks :)

**Comment by bgerstle** [comment]
@Danappelxx do you see coverage when you run tests via Xcode?  I've had issues getting code coverage when using xctool in the past, but maybe there's a way to get it to work. For now, I'd recommend getting it working with plain xcodebuild.  If you want pretty output, you can always pipe it through xcpretty (which is pre-installed on Travis).  Some other things to try:

- Specify the workspace to xcodebuild (`-workspace`)
- Pass `-enableCodeCoverage`
- Check "Gather code coverage" in your Xcode scheme's "Test" action's arguments
- Removing the GCC coverage flags (I don't think they're required anymore if you use `-enableCodeCoverage`)

**Comment by Danappelxx** [comment]
Using `xcodebuild` and passing the `enableCodeCoverage YES` flag did the trick! Thank you so much :smiley: 

One thing that's kind of bugging me is that codecov is reporting that my CI tests have failed, even though they've actually succeeded.

**Comment by bgerstle** [comment]
@Danappelxx glad it's working!  Do you have an example of the codecov failures?

**Comment by Danappelxx** [comment]
Sure - here's the [Travis Log](https://codecov.io/github/Danappelxx/SwiftMongoDB/commits) and here's the [Codecov](https://codecov.io/github/Danappelxx/SwiftMongoDB?ref=41e11bb215528847f373af080308e9680c2b22f7) for that commit. Notice how Travis said the build succeeded (it did), and codecov reported all the data successfully. However, on the codecov page, it has the red cross which states that CI tests have failed. It's not a big deal though since the coverage still gets reported correctly.

**Comment by bgerstle** [comment]
@stevepeak looks like codecov [hit a snag](https://travis-ci.org/Danappelxx/SwiftMongoDB#L1125) towards the end. Also, are there any plans to upload more conservatively? Looks like it's uploading test frameworks that should end up being ignored (Quick, Nimble, etc.).

**Comment by stevepeak** [comment]
@bgerstle looks like the [reports](https://codecov.io/github/Danappelxx/SwiftMongoDB?ref=2a464cca34566f80de1ab4d17990952450b408c9) made it up there :+1: Thank you for your help! I think I understand more how this works.

I'm not sure how to ignore reports in this case... I'm sure there is a way to detect what files are part of the project before uploading. But happy its working!

**Comment by bgerstle** [comment]
@stevepeak yeah, but the build is marked as a failure. any idea why?

**Comment by stevepeak** [comment]
Look like CircleCI failed, which caused Codecov to report a failure

> [Statuses](https://api.github.com/repos/Danappelxx/SwiftMongoDB/commits/2a464cca34566f80de1ab4d17990952450b408c9/statuses) See last line item

**Comment by Danappelxx** [comment]
I disabled CircleCI but the issue persists. Perhaps I didn't give it enough time - I'll try again in a few hours.

**Comment by stevepeak** [comment]
Hey @Danappelxx, checking in to see if this issue has been resolved. Thank you :+1:

**Comment by Danappelxx** [comment]
Yup! Works now :smiley:

**Comment by ravindrapatidar** [comment]
How do I configure codecov with Circle CI?

**Comment by stevepeak** [comment]
It should work out of the bot. Please make sure coverage is being collected according to the instructions in the [README](https://github.com/codecov/example-swift/blob/master/README.md)

**Comment by ravindrapatidar** [comment]
This example for Travis CI , I want to configure with Circle CI.

**Comment by stevepeak** [comment]
Circle CI integration is as straight-forward as Travis. You'll need to call the bash uploader at the end of your CI build script as a step in your circle.yml.

> @ravindrapatidar there are over 15 CI providers and over 20 languages. We would love an example for every combination (which would be 300 examples, not to mention other variables). Unfortunately, at this time we do not have the human resources to build this many examples. We hope to build more examples as we scale up our staff.
