### ISSUE TITLE
Is it compatible for Xcode version 6.4 

### ISSUE THREAD

**Issue by anilkumarbp** [codecov/example-swift#7]
I do not find a "Gather coverage data" in my test scheme.

Alternatively, i did follow the instructions posted here : https://github.com/codecov/example-xcode
But i am not able to include codecov into my project. Any help would be much appreciated. Thanks.

**Comment by stevepeak** [comment]
Can you checkout this post: http://www.egeek.me/2015/04/18/ios-test-code-coverage-report-on-jenkins/

Let me know if that works for you :) Thanks!

**Comment by stevepeak** [comment]
Hey @anilkumarbp checking in to see if you solved got this working. Let me know of the project you are trying this on so I can help you more.
