### ISSUE TITLE
Coverage data not gathered - No coverage data created for

### ISSUE THREAD

**Issue by cyupa** [codecov/example-swift#8]
I tried the implementation you suggest for swift with a simple project and it doesn't seem to upload any data to codecov.
```

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                                5ca7b8c
(url) https://codecov.io
(root) .
==> Travis CI detected.
  Found gcda in ~/Library/Developer/Xcode/DerivedData
    + Building reports for Calculator app
    + Building reports for CalculatorUITests-Runner app
error: Failed to load coverage: No such file or directory
    No coverage data created for /Users/travis/Library/Developer/Xcode/DerivedData/Calculator-bdgnglzeclfrejctupcexetpkjpe/Build/Intermediates/CodeCoverage/Coverage.profdata
    + Building reports for IDEBundleInjection framework
error: Failed to load coverage: No object file for requested architecture
    No coverage data created for /Users/travis/Library/Developer/Xcode/DerivedData/Calculator-bdgnglzeclfrejctupcexetpkjpe/Build/Intermediates/CodeCoverage/Coverage.profdata
    + Building reports for XCTest framework
error: Failed to load coverage: No object file for requested architecture
    No coverage data created for /Users/travis/Library/Developer/Xcode/DerivedData/Calculator-bdgnglzeclfrejctupcexetpkjpe/Build/Intermediates/CodeCoverage/Coverage.profdata
    + Building reports for XCTest framework
error: Failed to load coverage: No object file for requested architecture
    No coverage data created for /Users/travis/Library/Developer/Xcode/DerivedData/Calculator-bdgnglzeclfrejctupcexetpkjpe/Build/Intermediates/CodeCoverage/Coverage.profdata
    + Building reports for CalculatorTests xctest
    + Building reports for CalculatorUITests xctest
==> Trying gcov (disable via -X gcov)
  -> Running gcov
==> Searching for coverage reports
**> Python coverage not found
==> Detecting git/mercurial file structure
==> Reading reports
  + ./Calculator.app.coverage.txt bytes=9681
  + ./CalculatorTests.xctest.coverage.txt bytes=4339
  + ./CalculatorUITests.xctest.coverage.txt bytes=1852
==> Appending adjustments (http://bit.ly/1O4eBpt)
  --> Found 50 adjustments
(query) package=bash-5ca7b8c&branch=master&commit=1d56aecdc6aabedf18b67dc79a8efdbbe7a4b1fb&build=11.1&build_url=&slug=cyupa/Swift-Calculator&service=travis-org&pr=false&job=105805919
==> Uploading reports
    Pinging Codecov
    Uploading to S3
Reports queued to http://codecov.io/github/cyupa/Swift-Calculator?ref=1d56aecdc6aabedf18b67dc79a8efdbbe7a4b1fb
```

**Comment by stevepeak** [comment]
Hey @cyupa, I see the reports are being uploaded, but the coverage is reporting as all misses. This is found in the reports generated by XCode as well. 

The issue is going to be on XCode side and how the report data is collected. Can you make sure coverage is enabled properly, as described in this example repository. Thank you!

> [Here is the raw uploads](https://codecov.s3.amazonaws.com/repos/C637298153696808EB879FB37F67F904/uploads/upload:412385:1d56aecdc6aabedf18b67dc79a8efdbbe7a4b1fb:11.1:9398:1454113421.46.txt).

**Comment by cyupa** [comment]
I can confirm that the are enabled. https://github.com/cyupa/Swift-Calculator

**Comment by stevepeak** [comment]
Lets checkout these answers on Stack:

- http://stackoverflow.com/questions/33130551/no-coverage-data-after-configuring-test-scheme
- http://stackoverflow.com/questions/31096924/how-to-use-code-coverage-in-xcode-7

If these do not work I can call upon a friend to review. Thank you

> PS I'm not an xcode developer, pardon my ignorance.

**Comment by cyupa** [comment]
Hi Steve,
Thanks for your help. The suggestions do not apply, sadly. I will try to use slather - waiting for Travis to run the build.

**Comment by cyupa** [comment]
Still not working.

**Comment by cjwirth** [comment]
I agree, I'm having the same problem here. 
What's interesting though is that it works if I tell it to only upload 1 file:

```
> ./codecov.sh -f MyApp.app.coverage.txt -B master

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                                5ca7b8c


(url) https://codecov.io
(root) .
--> token set from env
==> Targeting specific file(s)
==> Detecting git/mercurial file structure
==> Reading reports
  + MyApp.app.coverage.txt bytes=3632186
==> Appending adjustments (http://bit.ly/1O4eBpt)
  --> Found 20245 adjustments
(query) package=bash-5ca7b8c&branch=master&commit=095563fada8d9b597cdf54ce6e229e6b029c7aa8&build=&build_url=&slug=&service=&pr=&job=&token=super-secret-token
==> Uploading reports
    Pinging Codecov
    Uploading to S3

Reports queued to http://codecov.io/github/myorg/myapp?ref=095563fada8d9b597cdf54ce6e229e6b029c7aa8
```

With this, the report shows up right away. :/

**Comment by cyupa** [comment]
I will give it a try locally to see how it behaves. Quite busy during the week.

**Comment by stevepeak** [comment]
@cjwirth `-f MyApp.app.coverage.txt` is a way to directly target results. However, this file was produced by Codecov and the file will be automatically included in the upload.

The issue @cyupa is having is during Codecov's attempt to generate the reports. Here is what I see:
- Reports are generated and found properly.
- The `No coverage data created for /...` may be more of a warning due to the technique of running tests. (I'm not very experienced in xcode testing).
- Codecov runs simple commands to generate the reports. See them here: https://github.com/codecov/codecov-bash/blob/master/codecov#L104-L132

**Comment by cjwirth** [comment]
> @cjwirth -f MyApp.app.coverage.txt is a way to directly target results. However, this file was produced by Codecov and the file will be automatically included in the upload.

Thanks. I understand that, and if I don't specify which file to run (i.e. I just run `./codecov.sh -B master`), it will generate all the `*.coverage.txt` files, then upload them all. My problem is that when it uploads all of them, nothing ends up being reported online. It's as if the upload fails (but the output said it succeeded). It _only_ works if I specify the file to upload.

**Comment by stevepeak** [comment]
@cjwirth interesting... do you have an example commit sha I can lookup to see why this is the case? If not, could you submit a new build with just `./codecov.sh -B master`

(ps why do you add `-B master`? The branch is detected too) Thanks!

**Comment by cjwirth** [comment]
> (ps why do you add -B master? The branch is detected too)

Ah, well that's good to know.

Unfortunately, I don't have anything I can show you. It's a private repo I'm working on for my company.

>  If not, could you submit a new build with just `./codecov.sh -B master`

You mean right now? Just did it right now, but with `./codecov.sh -D ./build`
I have nothing showing up in my Recent Commits.
 
However, then doing `./codecov.sh -D ./build -f MyApp.app.coverage.txt` , it showed up almost immediately (albeit with only the coverage information for MyApp).

**Comment by cjwirth** [comment]
If you can see things internally, the commit sha I just tried it with is 66282399d4ed073844944485e0f100b24b99475e . Do need more information than that?

Maybe it was taking a while to process the multiple-file upload, and then I overwrote it with the single-file upload? 🤔

**Comment by cjwirth** [comment]
Well I just tried with a [sample app](https://github.com/cjwirth/MyTestApp) and it looks like everything went well, I got the [results](https://codecov.io/github/cjwirth/MyTestApp) to show up just fine. 

There must be something really weird about our actual app?

**Comment by stevepeak** [comment]
> Maybe it was taking a while to process the multiple-file upload, and then I overwrote it with the single-file upload?

This is possible. I downloaded the raw reports and reviewed our logs. Looks like there was a small processing issue with a non-ascii character. Then I plugged the report into our next major release product and it came through great.

In the mean time, you can stick to whats working and we can revisit when the next release is live. 

Thanks!

**Comment by cjwirth** [comment]
>  Looks like there was a small processing issue with a non-ascii character. 

Aah, let me guess. ASCII control character 27 = escape? CircleCI won't let us download some XML artifact because that character shows up in there.

But you said _non_-ASCII, so maybe something Japanese? 

> Then I plugged the report into our next major release product and it came through great.

Excellent, I'm looking forward to it!

**Comment by cyupa** [comment]
Looking forward to the next release! :)

**Comment by stevepeak** [comment]
@cyupa @cjwirth have you seen this issue occur again?

**Comment by cyupa** [comment]
Hi @stevepeak I will give it a try. I looked a couple of days over this and thought I should give it a try again 👍

**Comment by cyupa** [comment]
Now it fails due to Travis CI not loading Slather. I will try it again on another project. Thanks for your message, @stevepeak

**Comment by stevepeak** [comment]
Are you running Codecov before Slather? Because I think Slather can get in the way of Codecov by removing Profdata.
