### ISSUE TITLE
Unable to gather code coverage for a given scheme

### ISSUE THREAD

**Issue by anilkumarbp** [codecov/example-swift#9]
Hi Team,

I have followed the exact steps outlined in your README.md to enable CodeCov on my swift project. 

Travis build is absolutely fine but I am unable to gather code coverage for the scheme.  

Below is the link to my CodeCov report page : 
https://codecov.io/github/anilkumarbp/ringcentral-swift-v2/

Is there anything that I would need to include as part of "Ignore Files" section within CodeCov repo. Appreciate your assistance on this. Thanks.

**Comment by stevepeak** [comment]
Hey @anilkumarbp I see there is coverage reports showing up on your project. What scheme is missing from the report? Do you have any tests written for the scheme?

**Comment by bay2** [comment]
Hi @stevepeak. My Xcode Version 7.3. My project uses UI Testing, Unable to gather code coverage.

**Comment by stevepeak** [comment]
@bay2 Checking in to see if this issue is resolved?
